### PR TITLE
Fix #48: Improve version reading & bump mxtheme dep version

### LINKED ISSUE #48: [Bug] ModuleNotFoundError: No module named 'sphinx'
When installing d2lbook in a completely new environment with sphinx not cached by previous pip installations, the following error is raised:

```bash
Collecting mxtheme>=0.3.16
  Downloading mxtheme-0.3.16.tar.gz (8.3 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/d2l-worker/miniconda3/envs/d2l-en-master-0/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g2gp4y2_/mxtheme_a6ceecb6302d4ebaa879512c5d3e27b6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g2gp4y2_/mxtheme_a6ceecb6302d4ebaa879512c5d3e27b6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-sjca2a5v
         cwd: /tmp/pip-install-g2gp4y2_/mxtheme_a6ceecb6302d4ebaa879512c5d3e27b6/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-g2gp4y2_/mxtheme_a6ceecb6302d4ebaa879512c5d3e27b6/setup.py", line 2, in <module>
        from mxtheme import __version__
      File "/tmp/pip-install-g2gp4y2_/mxtheme_a6ceecb6302d4ebaa879512c5d3e27b6/mxtheme/__init__.py", line 2, in <module>
        from .card import CardDirective
      File "/tmp/pip-install-g2gp4y2_/mxtheme_a6ceecb6302d4ebaa879512c5d3e27b6/mxtheme/card.py", line 1, in <module>
        from sphinx.locale import _
    ModuleNotFoundError: No module named 'sphinx'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ed/74/9bdb93269b054b9aefdc16b91e8ec8603afa16ba2036cdd5a10c5b0c9c71/mxtheme-0.3.16.tar.gz#sha256=e3524a6ea78f56686b14c866539aa49c8507b01ab414937454a7fbe6b55aaeac (from https://pypi.org/simple/mxtheme/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement mxtheme>=0.3.16 (from d2lbook) (from versions: 0.3.2, 0.3.3, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.13, 0.3.14, 0.3.15, 0.3.16)
ERROR: No matching distribution found for mxtheme>=0.3.16
script returned exit code 1
```

Attaching an example failed CI Log [here](http://ci.d2l.ai/blue/organizations/jenkins/d2l-en/detail/PR-2084/5/pipeline).
This is because d2lbook depends on sphinx and mxtheme is also one of the d2lbook dependencies which depends on sphinx.

### PR DESCRIPTION
**Pull request by AnirudhDagar**
Reference Issue: https://github.com/d2l-ai/d2l-book/issues/48
Reference Fix: https://github.com/mli/mx-theme/pull/8

A few minutes ago [mxtheme](https://github.com/mli/mx-theme/) was updated in https://github.com/mli/mx-theme/pull/8 to fix the root problem. Soon [mx-theme==0.3.17](https://pypi.org/project/mxtheme/) should be available on pypi. Once that is there, this PR can be merged and #48 can be closed.

cc @astonzhang @mli

### CODE REVIEW

**Comment by AnirudhDagar** [comment]
Ahh, this will break the CI atm since `mxtheme==0.3.17` is not yet up on pypi. hence i suggested to wait for that before merging. @mli could you please do that whenever you have time? Thanks!

**Comment by astonzhang** [comment]
@AnirudhDagar I've reverted this change https://github.com/d2l-ai/d2l-book/commit/0b1f63504d37dad7b1ab75aede6ae9c89f6398b6

Once mxtheme==0.3.17 is on pypi, could you resend this PR for merging?

**Comment by AnirudhDagar** [comment]
Cool, sounds good!

**Comment by mli** [comment]
uploaded mxtheme, please verify if the new version works

**Comment by AnirudhDagar** [comment]
I just ran a build on d2l-en [here](http://ci.d2l.ai/blue/organizations/jenkins/d2l-en/detail/PR-2030/6/pipeline) after deleting the environment manually. It is all green and the installation goes through smoothly, I can verify that the issue is resolved. Thanks Mu!

**Pull request merged**
